### ISSUE TITLE
AssertionError: num_classes (11) does not matches 80

### ISSUE THREAD

**Issue by Jhyunee** [2022-OpenSW/Team_proj#5]
### Error raised when running :

( running directory: mmdetection )
` python tools/train.py configs/_base_/default_runtime.py `

> AssertionError: The num_classes (11) in Shared2FCBBoxHead of MMDataParallel does not matches the length of CLASSES 80) in CocoDataset

**Comment by j-ys** [comment]
default_runtime.py 파일에
mmdet.datasets.coco.CocoDataset.CLASSES = ('onepiece(dress)', 'skirt', 'pants', 'jumpsuite',
           'shirt', 'sweater', 'blouse', 'cardigan', 'jumper', 'jacket', 'coat' )
위 코드 추가해서 CocoDataset.CLASSES override 하니 해결 완료 !!
